apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodeapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/nodeapp@sha256:e9503fe6d094f077845fdffb80f26bcb459c3126611a2f6b80b5d2d02fdc741d
        name: container-image
        resources: {}
status: {}
